@startuml microfinantare
entity BENEFICIAR
entity INVESTITOR
entity PROIECT
entity CERERE_FINANTARE
entity CONTRACT
entity INVESTITIE
entity PLAN_RAMBURSARE
entity RATA
entity DOMENIU
entity PROIECT_DOMENIU

BENEFICIAR "1" --- "N(1)" PROIECT
PROIECT "1" --- "1" CERERE_FINANTARE

INVESTITOR "1" --- "N(0)" INVESTITIE
PROIECT "1" --- "N(0)" INVESTITIE
CONTRACT "1" --- "N(0)" INVESTITIE

CONTRACT "1" --- "1" PLAN_RAMBURSARE
CONTRACT "1" --- "1" PROIECT
PLAN_RAMBURSARE "1" --- "N(1)" RATA

PROIECT "1" --- "N(0)" PROIECT_DOMENIU
DOMENIU "1" --- "N(0)" PROIECT_DOMENIU

@enduml